---    
- name: Install Docker CE 18.09
  apt: 
    update_cache: yes
    pkg:
      - docker-ce=5:18.09.1~3-0~ubuntu-bionic
      - docker-ce-cli=5:18.09.1~3-0~ubuntu-bionic

- name: Add key for NVIDIA CUDA repos
  apt_key:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    state: present

- name: Add repo for NVIDIA CUDA drivers
  apt_repository:
    repo: "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /"

- name: Install CUDA 11.0
  apt:
    name: ['cuda=11.0.2-1','cuda-11-0=11.0.2-1','cuda-runtime-11-0=11.0.2-1','cuda-drivers=450.51.05-1','cuda-drivers-450=450.51.05-1']
    state: present
    install_recommends: no
    update_cache: yes

- name: Install nvidia docker apt key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: Add nvidia-docker sources list
  get_url:
    url: https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Install nvidia-docker2
  apt:
    name: nvidia-docker2
    state: latest
    update_cache: yes

- name: Create jenkins user
  user:
    name: jenkins
    groups:
      - docker
      - wheel
    uid: 1001
    append: yes

- name: Add authorized keys
  authorized_key:
    user: jenkins
    key: '{{ item }}'
  with_file:
    - ../../common/files/goai-gpuci.id_rsa.pub
    - ../../common/files/jenkins-main.id_rsa.pub
    - ../../common/files/jenkins-aws-main.id_rsa.pub

- name: Initialize git-lfs
  command: git lfs install
  become: yes
  become_user: jenkins

- name: Reboot
  reboot: {}
